---
title: "ggplot2 PLOTS"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

## Problem 1
#Calcutt, S. E., Proctor, D., & Berman, S. M. (2019). Chimpanzees (Pan troglodytes) Are More Averse to Social Than Nonsocial Risk. Psychological Science, 30, 105-115.


```{r}
#Dataframe
Names<-rep(c("Dara","Rita","Liza","Azalea","Barbi", "Rowena", "Fiona", "Katie"),each=2)
Adversity<-rep(c("Not_Advers","Advers"),times=c(6,10))
Conditions<-rep(c("Social","Not_Social"),8)
MeanFreq<-runif(16,1,70)
A<-data.frame(Names,Adversity,Conditions)

#ggplot
ggplot(A,aes(x=Conditions,y=MeanFreq,group=Names,linetype=Adversity))+geom_line()+geom_text(label=Names)+theme_classic()

```

## Problem 2
# Cao, J., Kleiman-Weiner, M., & Banaji, M. R. (2019). People Make the Same Bayesian Judgment They Criticize in Others. Psychological Science, 30, 20-31.nm


```{r}
#Dataframe
Aver_Freq_SC<-rnorm(7,35,70)
Aver_Freq_NonSC<-rnorm(7,35,70)
B<-data.frame(Aver_Freq_SC,Aver_Freq_NonSC)

#ggplot
ggplot(B,aes(x=Aver_Freq_NonSC,y=Aver_Freq_SC))+
  geom_point()+geom_smooth(method=lm)
```

##Problem 3
```{r}
#Create a dataframe

X_Axis<-as.factor(c("Doctor Study 1 N=199", "Butcher Study 2 n=199", "Firefighter Study 2 n=200", "Construction Worker Study 2 n=2"))

Stacked_factors<-as.factor(c("Man More Likely", "Equal Likely", "Women More Likely", "NnAa"))

"Man More Likely"<-c(7,35,40,40)
"Equal Likely"<-c(93,60,59,57)
"Women More Likely"<-c(0,5,1,3)
"NnAa"<-c(0,0,0,0)

"Percentage of Participants"<-sample(0:100,replace = T)

Data_C<-data.frame(X_Axis,Stacked_factors,"Percentage of Participants")


# basic bar graph
ggplot(Data_C)+ geom_bar(aes(x=X_Axis, fill=Stacked_factors))


ggplot(Data_C, aes(x=X_Axis,y="Percentage of Participants"))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin="Percentage of Participants"-Stacked_factors,
ymax="Percentage of Participants"+Stacked_factors), width=.2)+
  coord_cartesian(ylim=c(0,100))+
  xlab("X_Axis")+
  ylab("Stacked_factors")+
  theme_classic(base_size=12)+
  theme(plot.title = element_text(hjust = 0.5))

```

##Problem 4

```{r}
#Create a dataframe

Person_X_Answer<- as.factor(c("Equal Likely n=200","Man More Likely n=202", "NaNa"))

Money_Transferred_to_Person_X<-as.factor(c(0.00,0.15,0.30))

Data_D<-data.frame(Person_X_Answer,Money_Transferred_to_Person_X)


# basic bar graph

ggplot(Data_D, aes(x=Person_X_Answer,y=Money_Transferred_to_Person_X))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=Person_X_Answer-Money_Transferred_to_Person_X,
                    ymax=Person_X_Answer+Money_Transferred_to_Person_X),
                width=.2)+
  coord_cartesian(ylim=c(0,100))+
  xlab(Person_X_Answer)+
  ylab(Money_Transferred_to_Person_X)+
  ggtitle("Bar graph with Error Bars")+
  theme_classic(base_size=12)+
  theme(plot.title = element_text(hjust = 0.5))

```







